Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -49,51 +49,25 @@ jobs:
     runs-on: self-hosted
     steps:
     - name: Kill previous instance if exists
-    run: |
-      max_retries=5
-      count=0
-      while sudo lsof -t -i:443 && [ $count -lt $max_retries ]; do
-        echo "Attempting to kill process on port 443. Try #$count"
-        sudo kill -9 $(sudo lsof -t -i:443) || true
-        count=$((count + 1))
-        sleep 5
-      done
-      if [ $count -eq $max_retries ]; then
-        echo "Failed to kill process on port 443 after $max_retries attempts."
-        exit 1
-      fi
-
-  
-    - name: Execute Jar File
-      run: sudo java -jar /home/ubuntu/actions-runner/_work/storage-s3/storage-s3/s3/target/s3-0.0.1-SNAPSHOT.jar > app_log.txt 2>&1 &
-  
-    - name: Monitor Application Logs for Start/Error
       run: |
-        timeout_duration=60  # 1 minutes in seconds
-        check_interval=10     # check every 10 seconds
-        total_wait=0
-  
-        while [ $total_wait -lt $timeout_duration ]; do
-          # Check for your specific startup message. Replace "YourStartupMessageHere" accordingly.
-          if grep -q "YourStartupMessageHere" app_log.txt; then
-            echo "Application started successfully!"
-            exit 0
-          fi
-          
-          # Check for errors or exceptions. Adapt as necessary.
-          if grep -E -q "Exception|Error" app_log.txt; then
-            echo "Error detected in application logs!"
-            tail -n 50 app_log.txt
-            exit 1
-          fi
-  
-          sleep $check_interval
-          total_wait=$((total_wait + check_interval))
+        max_retries=5
+        count=0
+        while sudo lsof -t -i:443 && [ $count -lt $max_retries ]; do
+          echo "Attempting to kill process on port 443. Try #$count"
+          sudo kill -9 $(sudo lsof -t -i:443) || true
+          count=$((count + 1))
+          sleep 5
         done
-  
-        echo "Deployment timeout: Application did not start successfully within 6 minutes."
+        if [ $count -eq $max_retries ]; then
+          echo "Failed to kill process on port 443 after $max_retries attempts."
+          exit 1
+        fi
+    - name: Execute Jar File
+      run: |
+        sudo java -jar /home/ubuntu/actions-runner/_work/storage-s3/storage-s3/s3/target/s3-0.0.1-SNAPSHOT.jar > app_log.txt 2>&1 &
+        sleep 10
         tail -n 50 app_log.txt
-        exit 1
+
   
   # Test Job
   test:
