Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -47,29 +47,30 @@ jobs:
     steps:
     - name: Kill previous instance if exists
       run: |
-        set -euxo pipefail  # This makes the script verbose and fail on the first error
+        sudo kill -9 $(sudo lsof -t -i:8080) || true
+        # set -euxo pipefail  # This makes the script verbose and fail on the first error
         
-        PIDS=$(pgrep java || true)  # Use || true to avoid the script from failing when pgrep returns no PIDs
+        # PIDS=$(pgrep java || true)  # Use || true to avoid the script from failing when pgrep returns no PIDs
         
-        # Loop over each PID to handle them separately
-        for PID in $PIDS; do
-          echo "Java process found with PID $PID. Attempting to terminate..."
+        # # Loop over each PID to handle them separately
+        # for PID in $PIDS; do
+        #   echo "Java process found with PID $PID. Attempting to terminate..."
       
-          # Graceful shutdown with a 10-second timeout
-          sudo kill $PID || (echo "Error trying to gracefully terminate Java process with PID $PID" && exit 1)
-          sleep 10
+        #   # Graceful shutdown with a 10-second timeout
+        #   sudo kill $PID || (echo "Error trying to gracefully terminate Java process with PID $PID" && exit 1)
+        #   sleep 10
       
-          # Check if the process is still running, and force kill if necessary
-          if ps -p $PID > /dev/null; then
-            echo "Java process with PID $PID did not terminate gracefully. Force killing..."
-            sudo kill -9 $PID || (echo "Error force killing Java process with PID $PID" && exit 1)
-          fi
-        done
+        #   # Check if the process is still running, and force kill if necessary
+        #   if ps -p $PID > /dev/null; then
+        #     echo "Java process with PID $PID did not terminate gracefully. Force killing..."
+        #     sudo kill -9 $PID || (echo "Error force killing Java process with PID $PID" && exit 1)
+        #   fi
+        # done
   
-        # If no PIDs were found
-        if [[ -z "$PIDS" ]]; then
-          echo "No Java process found running."
-        fi
+        # # If no PIDs were found
+        # if [[ -z "$PIDS" ]]; then
+        #   echo "No Java process found running."
+        # fi
     - name: Execute Jar File
       run: |
         sudo java -jar /home/ubuntu/actions-runner/_work/storage-s3/storage-s3/s3/target/s3-0.0.1-SNAPSHOT.jar > app_log.txt 2>&1 &
