Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -44,23 +44,18 @@ jobs:
     #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d
 
   # Deploy Job
+  # Deploy Job
   deploy:
     needs: build
     runs-on: self-hosted
     steps:
     - name: Kill previous instance if exists
       run: |
-        max_retries=5
-        count=0
-        while sudo lsof -t -i:443 && [ $count -lt $max_retries ]; do
-          echo "Attempting to kill process on port 443. Try #$count"
-          sudo kill -9 $(sudo lsof -t -i:443) || true
-          count=$((count + 1))
-          sleep 5
-        done
-        if [ $count -eq $max_retries ]; then
-          echo "Failed to kill process on port 443 after $max_retries attempts."
-          exit 1
+        if sudo lsof -t -i:443; then
+          echo "Found a process running on port 443. Attempting to kill..."
+          sudo kill -9 $(sudo lsof -t -i:443) || echo "Failed to kill process on port 443. Proceeding anyway."
+        else
+          echo "No process found on port 443."
         fi
     - name: Execute Jar File
       run: |
