fixing a looping in kill port 443

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -49,7 +49,20 @@ jobs:
     runs-on: self-hosted
     steps:
     - name: Kill previous instance if exists
-      run: sudo kill -9 $(sudo lsof -t -i:443) || true
+    run: |
+      max_retries=5
+      count=0
+      while sudo lsof -t -i:443 && [ $count -lt $max_retries ]; do
+        echo "Attempting to kill process on port 443. Try #$count"
+        sudo kill -9 $(sudo lsof -t -i:443) || true
+        count=$((count + 1))
+        sleep 5
+      done
+      if [ $count -eq $max_retries ]; then
+        echo "Failed to kill process on port 443 after $max_retries attempts."
+        exit 1
+      fi
+
   
     - name: Execute Jar File
       run: sudo java -jar /home/ubuntu/actions-runner/_work/storage-s3/storage-s3/s3/target/s3-0.0.1-SNAPSHOT.jar > app_log.txt 2>&1 &
